# 基础镜像
FROM  openjdk:8-jre

# 挂载目录
VOLUME /home/demo
# 创建目录
RUN mkdir -p /home/demo
# 指定路径
WORKDIR /home/demo
# 复制jar文件到路径
COPY ./jar/auth-1.0.0.jar /home/demo/auth-1.0.0.jar
# 启动认证服务
ENTRYPOINT ["java","-jar","auth-1.0.0.jar"]
